### ISSUE TITLE
GraphqlError: Field 'createLabel' doesn't exist on type 'Mutation'

### ISSUE THREAD

**Issue by ScottChapman** [octokit/graphql.js#135]
So, I'm trying to migrate from using the request object from `@octokit/rest.js` to make graphql calls like this:
```javascript
const query = `mutation createLabel {
    createLabel(input: {
      repositoryId: "<repoID>",
      name: "<labelname>",
      color: "<labelcolor>",
      description: "<labeldescription>"
    }) {
      label {
        id
      }
    }}
      `;
    console.log(query)
    const resp = await octokit.request("POST /graphql",{query})
```
That works like a champ. But trying to re-factor to use this:
```javascript
const query = `mutation createLabel {
    createLabel(input: {
      repositoryId: "<repoID>",
      name: "<labelname>",
      color: "<labelcolor>",
      description: "<labeldescription>"
    }) {
      label {
        id
      }
    }}
      `;
    console.log(query)
    const resp = await graphql(query)
```
That does NOT work. It gives me the following error:
`GraphqlError: Field 'createLabel' doesn't exist on type 'Mutation'`

What am I doing wrong??

**Comment by gr2m** [comment]
If you used `octokit.request` before, you can use `octokit.graphql`, it will inherit the same authentication and request settings.

The error makes no sense to me ... very odd! Does it work when you paste it 1:1 into https://developer.github.com/v4/explorer/?

**Comment by ScottChapman** [comment]
yea! That's how I develop my graphql. Does someone have an example of the above that works?

**Comment by gr2m** [comment]
I get the same error in the explorer

<img width="616" alt="image" src="https://user-images.githubusercontent.com/39992/87180490-7b229100-c295-11ea-94da-6ce8b5e0cd2f.png">

THere is a preview you need to set in order to use the `createLabel` mutation:
https://docs.github.com/en/graphql/overview/schema-previews#labels-preview

You can do that like this

```js
const query = `mutation createLabel {
  createLabel(input: {
    repositoryId: "<repoID>",
    name: "<labelname>",
    color: "<labelcolor>",
    description: "<labeldescription>"
  }) {
    label {
      id
    }
  }}
    `;
console.log(query);
const result = await graphql(query, { mediaType: { previews: ["bane"] } });
```

You might also want to use variables

```js
const query = `mutation createLabel($repositoryId: ID!, $name: String!, $color: String, $description: String) {
  createLabel(input: {repositoryId: $repositoryId, name: $name, color: $color, description: $description}) {
    label {
      id
    }
  }
}`;
const result = await graphql(query, {
  repositoryId,
  name,
  color,
  description,
  mediaType: { previews: ["bane"] },
});

```

**Comment by ScottChapman** [comment]
Damn it! I was pretty sure I crafted it that way. Thanks for being a co-pilot
