### ISSUE TITLE
Handling partial data with error(s)

### ISSUE THREAD

**Issue by TimonVS** [octokit/graphql.js#14]
In some cases the API might return partial data with an error, e.g.:

```json
{
  "data": {
    "repository": {
      "ref": null
    }
  },
  "errors": [
    {
      "type": "INVALID_CURSOR_ARGUMENTS",
      "path": [
        "repository",
        "ref",
        "target",
        "history"
      ],
      "locations": [
        {
          "line": 6,
          "column": 11
        }
      ],
      "message": "`123` does not appear to be a valid cursor."
    }
  ]
}
```

https://github.com/octokit/graphql.js/blob/master/lib/graphql.js#L30 suggests that when the API returns partial data and an error it will just return the data. Now my question is, how can I know that the API returns an error? As far as I can see I can't get access to the error object.

**Comment by gr2m** [comment]
Could you maybe make a RunKit notebook reproducing the problem, using nock to mock the response? Or start a pull request with a failing test? You could add it here: https://github.com/octokit/graphql.js/blob/master/test/error-test.js

That would help me to look into it faster 🙏

**Comment by TimonVS** [comment]
Sure, I’m sorry for not doing that right away 😅. I’ll get on it ASAP.

**Comment by TimonVS** [comment]
I've created a reproduction here: https://github.com/TimonVS/graphql.js/blob/partial-data-error-repro/test/error-test.js#L51

If you run the test it will throw you'll notice that it fails on this line: https://github.com/TimonVS/graphql.js/blob/partial-data-error-repro/test/error-test.js#L103, which means that `graphql` didn't throw an error even though there are errors in the response. I'm wondering how should we handle partial data with errors? Throwing might not always make sense because the partial data might actually be useful, but if you don't throw then there's no way to know there's an error since `result` (on https://github.com/TimonVS/graphql.js/blob/partial-data-error-repro/test/error-test.js#L102) only contains the data from `mockResponse` and not the errors array.

**Comment by gr2m** [comment]
The test looks great 👍 Could you start a pull request and we take it from there?

> I'm wondering how should we handle partial data with errors? 

Good question, clearly a case I did not consider yet. Right now I think I would throw the error, but add `error.data` with the partial response

**Comment by TimonVS** [comment]
Created a PR here: https://github.com/octokit/graphql.js/pull/15

**Comment by gr2m** [comment]
fixed via https://github.com/octokit/graphql.js/pull/15
