### ISSUE TITLE
rate-limit tools

### ISSUE THREAD

**Issue by iliakan** [octokit/graphql.js#17]
Is there any baked-in solution that allows to wait if rate-limit exceeded?

Or just any rate-limit interaction?

**Comment by gr2m** [comment]
Not directly for the `@octokit/graphql` method. But we do have a plugin for `@octokit/rest`: https://github.com/octokit/plugin-throttling.js

Let me get back to you on how to use the plugin with `@octokit/graphql`, it’s not straight forward at this point. I’m currently working on other things so it will take a while I’m afraid. But if you want to look into it yourself and have any questions, I’d be happy to help you out

**Comment by iliakan** [comment]
That's looks straingt to the point!

Should I use `@octokit/rest` instead of `@octokit/graphql`?

**Comment by gr2m** [comment]
https://github.com/octokit/plugin-throttling.js does include special throttling for `@octokit/graphql` now. It’s still not usable with `@octokit/rest`, but if you don’t want to wait, here is how we use it in probot:

https://github.com/probot/probot/blob/8f86e8d1c82f7ac94899f97b0104fa9a8b7c5b48/src/github/graphql.ts#L18-L22

Note that it’s using internal APIs, so make sure to pin the `@octokit/graphql` version for the time being

**Comment by gr2m** [comment]
I'm working on the Octokit Core library which will include the `.graphql` method, but also the plugin API. So you will be able to load the throttle plugin.

Initial version should be ready soon: https://github.com/octokit/core.js/pull/3

**Comment by foolip** [comment]
https://github.com/octokit/core.js/pull/3 is resolved now, does that mean this is ready for action now? Examples of how to integrate with `@octokit/graphql` would be great!

**Comment by gr2m** [comment]
I'm open to suggestions. Throttling with GraphQL is much more complicated then it is with REST. @ReaLoretta gave a great talk on advanced GraphQL patterns such as this at GitHub Universe: https://www.youtube.com/watch?v=i5pIszu9MeM.

We are looking into creating a GraphQL pagination plugin too: https://github.com/octokit/plugin-paginate-graphql.js/pull/1

**Comment by kevindigo** [comment]
We're about to dive into some octokit graphql work. What is the recommended way to perform simple throttling/rate limiting at this point?

**Comment by gr2m** [comment]
Use the [throttle plugin](https://github.com/octokit/plugin-throttling.js#readme), it has some throttle logic specific to GraphQL built in, but I don't think it covers it all yet. As mentioned above GraphQL is much more complicated compared to the REST API, throttling alone won't help you if your queries are to complex. Make sure to watch Rea's talk that I've linked above.

The original issue is resolved, so I'm going to close the issue. `@octokit/rest` is now built on `@octokit/core`, both can utilize the throttle plugin in the same way.

**Comment by dan-kez** [comment]
Apologies for pulling on an old thread, I've been looking through the repo and it's not clear to me how to integrate a plugin with the current graphql implementation. Is there a way to pass an Octokit instance to this library that I am missing?

**Comment by gr2m** [comment]
This library exports a stateless `graphql` function. You can use [`@octokit/core`](https://github.com/octokit/core.js/#readme), which includes the `octokit.graphql` method on each instance

**Comment by gr2m** [comment]
https://github.com/octokit/plugin-throttling.js/ and https://github.com/octokit/plugin-retry.js now both handle GraphQL queries. We recommend you use the `octokit` package which has it all included

```js
import { Octokit } from "octokit"
const octokit = new Octokit({ auth: TOKEN })
const result = await octokit.graphql(query, variables)
```

**Comment by Mickaz89-SWM** [comment]
In order to use the plugin-throttling , we moved from the @octokit/graphql pacakge to the "octokit" package like the example . We now able to use throttle with graphal but we are getting now a warning in the console browser : 

<img width="652" alt="Screenshot 2024-08-11 at 10 45 15" src="https://github.com/user-attachments/assets/eebd31ba-9e4e-433a-9949-b4a27f563a82">

Someone know why the browser interpret the module as Node Js module ?

**Comment by wolfy1339** [comment]
Please use the ESM.sh build for browser usage.

```js
import { Octokit } from "https://esm.sh/octokit";
```
