### ISSUE TITLE
Allow orderBy of PullRequests by mergedAt

### ISSUE THREAD

**Issue by goncalvesnelson** [octokit/graphql.js#191]
Hi, 
Would it be possible to extend the graphQL API to allow sorting the list of pull requests by mergedAt?

This would be very helpful in automating the creation of CHANGELOG files since it would allow us to:
1. Use the API to fetch the createdAt timestamp of the last release
2. Get the list of PRs sorted by mergedAt and iterate through that list, saving each PR until we find the first PR with mergedAt timestamp before the timestamp of the last release. 

This would save us from having to fetch all the PRs.  

Thank you.

**Comment by gr2m** [comment]
What's your current query? 

I cannot help with extending GitHub's GraphQL Schema. The best place to ask about that is https://github.community/c/github-api-development-and-support/37 or to send a Support request at https://support.github.com/contact

The `@octokit/graphql` library that we maintain in this repository is just a light wrapper around GitHub's GraphQL API

**Comment by goncalvesnelson** [comment]
Hi @gr2m.
Thanks for replying! 
My query is the following:

```
query pullRequestsBefore($owner: String!, $repo: String!, $first: Int!, $base: String!, $cursor: String!) {
      repository(owner: $owner, name: $repo){
        pullRequests(baseRefName: $base,  first: $first, orderBy: {field: UPDATED_AT, direction: DESC}, states: [MERGED], after: $cursor) {
          nodes {
            mergedAt
            title
            number
            url
            baseRefName
            author{
              login
              url
            }
          }
          pageInfo {
            endCursor
            hasNextPage
          }
        }
      }
    }`;
```

I first fetch the last release and then, using the query above I fetch the list of PRs (which I would like to have sorted by mergedAt in reversed order) in order to get all the PRs that have been merged after the last release was created. 
The issue is that you can only sort by createdAt or updatedAt, both of which cannot be used for this purpose. PRs can be merged in a different order from the one they were created and PRs can be updated after being merged.  This means that the only reliable way to make sure you get all the PRs that were merged after a given release is to get the list of all PRs which can be slow in a repo with lots of activity.

**Comment by gr2m** [comment]
I see, so you would like to `orderBy.fields` for `repository.pullRequests()` to support a new field: `MERGED_AT`. I'm afraid I cannot help with that. [The equivalent REST API endpoint](https://docs.github.com/en/rest/reference/pulls#list-pull-requests) does not have that option either.

I recommend contacting support: https://support.github.com/contact. They will file your request and will let you know if that is something they consider adding in future.

I'll close this issue as there is nothing actionable for the `@octokit/graphql` library, but please feel free to comment if you have more questions
