### ISSUE TITLE
`GraphQlQueryResponseData` type not exposed when package is published

### ISSUE THREAD

**Issue by oscard0m** [octokit/graphql.js#254]
**What happened?**
When trying to import `GraphQlQueryResponseData` type from `@octokit/graphql.js` is not possible because it is not exposed. Only `graphql` interface inside `types.ts` is exported

**What did you expect to happen?**
To be able to import it directly from the lib without accessing `dist-types/` folder
 
**What the problem might be**
Pika plugin when generating types exposure

**Comment by gr2m** [comment]
To make that work, we would need to export `GraphQlQueryResponseData` in `src/index.ts`

I wouldn't consider this a bug though, it's not currently documented that it would work. So I think this is rather a feature request? I don't mind adding it, but maybe also document it in the README if you want to send a pull request?
