### ISSUE TITLE
GraphQL API cursor pagination error: any hints

### ISSUE THREAD

**Issue by vvo** [octokit/graphql.js#261]
Hi there, I am using @octokit/graphql, congrats on the library it's the right API (I have tried graphql-request before and it was too complex around variables + auth).

I am paginating through multiple results (using your technique in https://github.com/octokit/graphql.js/issues/61#issuecomment-643392492) and at some point I get this error:

> 'Something went wrong while executing your query. Please include \`E439:DB8E:47FB1C:498D51:603D09DA\` when reporting this issue.'

Did you ever encounter it?

Here's the query:

```
query {
  user(login: "vvo") {
    issueComments(last: 4, before: "Y3Vyc29yOnYyOpHOEKo5gw==") {
      nodes {
        resourcePath
      }
    }
  },
}
```

If I ask only the last 3 nodes then it works:

```
query {
  user(login: "vvo") {
    issueComments(last: 3, before: "Y3Vyc29yOnYyOpHOEKo5gw==") {
      nodes {
        resourcePath
      }
    }
  },
}
```

I understand this is out of the scope of your library and most probably a GitHub bug, but maybe you do have a hint.

Thanks!

**Comment by gr2m** [comment]
> 'Something went wrong while executing your query. Please include `E439:DB8E:47FB1C:498D51:603D09DA` when reporting this issue.'

In cases such as this I would reach out to support directly:
https://support.github.com/contact

For questions about GitHub's platform APIs or problems with the APIs that are likely not related to Octokit, the GitHub Ecosystem Community forum is a great place to ask for help: https://github.community/c/github-ecosystem/37

**Comment by vvo** [comment]
Works for me, thanks
