### ISSUE TITLE
'used by' field on repo object

### ISSUE THREAD

**Issue by hughrawlinson** [octokit/graphql.js#27]
Hi,

Please delete this issue if this isn't the right place to submit feature requests for the GitHub GraphQL API. If you can point me to the right place, even better!

I'm working on an app that displays all a users repositories in a sortable and filterable table so that they can easily identify issues with their repos setup, and prioritize fixes (like "all non-archived repos should be tagged and have <x security vulnerabilities"). I saw the new "used by" badge on GitHub repositories - great stuff! I would love to add a column for this to my app, because I think it would be a good heuristic for prioritizing fixes. I haven't been able to find a way to access this data with the GraphQL API - only dependencies (rather than dependents) are available.

FWIW, I've worked with triaging on public feature requests issue trackers for APIs, and I feel like I should clarify that this is really just a suggestion, and I don't expect it to happen soon, but it would be nice if it happened at all :smile: 

Thanks!

Hugh

**Comment by gr2m** [comment]
Hi Hugh,

this repository is just a client for the GraphQL.

Good places to ask your question are

- https://github.community/
- https://github.com/support

Have a nice weekend :)
