### ISSUE TITLE
Avoid setting `user-agent` when on the web or allow an opt-out?

### ISSUE THREAD

**Issue by eamodio** [octokit/graphql.js#278]
Currently `graphql.js` always tries to set the `user-agent` for the outgoing requests. And I am seeing an `Refused to set unsafe header "user-agent"` error on every request in the devtools console.

Is there a way around this?

**Comment by gr2m** [comment]
What browser / version are you using? I never heard that setting user agent is not permitted

**Comment by eamodio** [comment]
Latest Edge (Chromium) and I believe others are seeing it on Chrome as well.

**Comment by gr2m** [comment]
This is getting really odd, is it possible that it depends on the site's own security settings?

Try running this code on https://example.com

```js
fetch("https://api.github.com", {
  headers: {
    'User-Agent': 'my user agent'
  }
})
```

I don't see any warning in my developer console, but it seems setting the `user-agent` has no effect? I tried to find a resource about the web standards no longer permitting to set this header in browsers, or any other official documentation on this, but no luck. Do you know of any?

**Comment by eamodio** [comment]
It seems like `user-agent` is no longer forbidden, but only Firefox has caught up with the spec: https://developer.mozilla.org/en-US/docs/Glossary/Forbidden_header_name

**Comment by gr2m** [comment]
In that case I think I'd rather not change anything and wait until the browsers catch up. I'll close the issue but please feel free to continue to comment if you think I should reconsider

**Comment by eamodio** [comment]
Digging into this more -- I believe the issue is that I am using this in a WebWorker, and they aren't allowed to set the `user-agent` AFAICT. Can an option be added to suppress this?

**Comment by gr2m** [comment]
that'd be so odd, why? If you could get to the bottom of this, I'd appreciate it. If setting the user agent prevents octokit to be used from webworkers, I'd be happy to look into that. But I'm sure I've used plenty of octokit in web workers and service workers without problems in the past

**Comment by eamodio** [comment]
It works fine, it just litters the error console with errors -- which makes it really hard to see real errors.
