### ISSUE TITLE
Managing PAT in a browser environment

### ISSUE THREAD

**Issue by TomokiMiyauci** [octokit/graphql.js#298]
H! Thanks for the great project.

The project runs only in a browser environment, such as SPA,
PAT will be bundled and technically accessible.

Should I hide the PAT on the server side even if I use no scoped PAT?

**Comment by gr2m** [comment]
> Should I hide the PAT on the server side even if I use no scoped PAT?

It depends on what you are building. If you want your users to be authenticated as themselves, then you will need the access token in the browser. If you use it only to increase the rate limit for fixed queries on the server side, then you can hide it in the server.

There is nothing actionable for us to do here so I'm going to close the issue, but feel free to ask follow up questions

**Comment by TomokiMiyauci** [comment]
I am trying to use a static site generator like Gatsby to get the number of comments on an issue associated with a blog post, on the client side.

I probably shouldn't have asked this question here, but...
The essence of this question is whether there is a problem with no scoped PAT being leaked.

**Comment by gr2m** [comment]
>  The essence of this question is whether there is a problem with no scoped PAT being leaked.

yes someone else might drain your rate limit and lock you out from using anything else with your account. I can't think of anything else, but yeah better don't let it leak

**Comment by TomokiMiyauci** [comment]
I asked this question due to security concerns.
Thanks for answering!
