### ISSUE TITLE
missing fields in PackageVersion

### ISSUE THREAD

**Issue by tcastelly** [octokit/graphql.js#304]
Hello,

The REST Api allow to retrieve dates for a package version:
- created_at
- updated_at

I'm wondering if these fields can be implemented in PackageVersion graph.

**Comment by gr2m** [comment]
Hi @tcastelly, this is the wrong place to ask I'm afraid. This repository is just a JavaScript method to send queries to GitHubs GraphQL API. I recommend to contact support at https://support.github.com/contact or to create a post in the GitHub API forum at https://github.community/c/github-ecosystem/37
