### ISSUE TITLE
HttpError: Integration not found

### ISSUE THREAD

**Issue by kevinkowa** [octokit/graphql.js#320]
Hi, I'm getting the following error `HttpError: Integration not found` when running a graphql query. This only happens when the repository is private, otherwise it works. I'm using an installationId to authenticate.
```
const auth = createAppAuth({
    appId: configuration.githubAppId,
    installationId,
    privateKey: configuration.githubAppPrivateKey,
  });

  const enterpriseGraphQL = graphql.defaults({
    baseUrl: '{enterprise_url},
    request: {
      hook: auth.hook,
    },
  });
```
query looks like this. Where repositoryName and repositoryOwner is retrieved from an installation event
```
repository(name: "${repositoryName}", owner: "${repositoryOwner}") {
        databaseId
        description
        isPrivate
        name
        url
        defaultBranchRef {
          target {
            ... on Commit {
              history(first: 1) {
                nodes {
                  committedDate
                }
              }
            }
          }
        }
...
```

Can you guys turn me to the right direction here?

**Comment by gr2m** [comment]
I'm not sure what the problem might be I'm afraid, I have not seen this error myself before. The code looks good.

Can you maybe create the installation access token and then use it with a non-octokit tool to send the query, e.g. https://www.electronjs.org/apps/graphiql? If you get the same error, it's not related to Octokit and I'd recommend to contact support

**Comment by kevinkowa** [comment]
Thanks, looks like it was a permission issue
