### ISSUE TITLE
Unable to compile project, graphql package is giving TS errors

### ISSUE THREAD

**Issue by papaiatis** [octokit/graphql.js#327]
Hey,

I added `octokit/graphql` package to my project and since then I'm unable to build it, getting the following errors:

![image](https://user-images.githubusercontent.com/3688096/136441473-3e2e2ace-7d7c-43c4-970d-0e36bc110d0b.png)

I have the following octokit packages installed:

![image](https://user-images.githubusercontent.com/3688096/136442386-6062f218-697c-4f58-809d-db81a46241c7.png)

I have `typescript@3.8.3` in my project and I cannot upgrade to v4+ due to having a large code base and there are hundreds of errors with TS v4+.

Content of `tsconfig.json`:

```
{
  "compilerOptions": {
    "module": "CommonJS",
    "moduleResolution": "node",
    "esModuleInterop": true,
    "emitDecoratorMetadata": true,
    "forceConsistentCasingInFileNames": true,
    "experimentalDecorators": true,
    "target": "es2019",
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./src",
    "incremental": true,
    // paths are relative to the baseUrl ('./')
    "paths": {
      "shared/*": ["../../shared/*"]
    },
    "rootDir": "../",
    "strict": true,
    "allowJs": true,
    "resolveJsonModule": true
  },
  "include": ["../shared", "./src"],
  "exclude": ["node_modules", "dist"]
}
```

Any clue what could be wrong or how to fix it?
Thanks!

**Comment by gr2m** [comment]
Can you try setting `compilerOptions.strictNullChecks` to `true`?

> I have `typescript@3.8.3` in my project and I cannot upgrade to v4+ due to having a large code base and there are hundreds of errors with TS v4+.

We only support TS v4, sorry. You will have to upgrade eventually. Our types are very complex, and we rely on the latest TS to make them work.
