### ISSUE TITLE
Requests for Projects (Beta) via graphql return wrong results

### ISSUE THREAD

**Issue by apsamuel** [octokit/graphql.js#334]
When using the octokit graphql module, I'm getting an incorrect result returned when querying for `projectNext` (Projects Beta) on GitHub.

## octokit/graphql (returns null values)

```
> await o.graphql(`query { organization(login: "myorg"){ projectNext(number: 111) { id}} }`, {owner: "myorg"})
{ organization: { projectNext: null } }
```

## octokit/graphql (successful against other resources)

```
> await o.graphql(`query { viewer { login}}`)
{ viewer: { login: 'apsamuel' } }
```

## GraphQL Explorer (successful) 

<img width="1183" alt="Screen Shot 2022-02-08 at 11 49 00 AM" src="https://user-images.githubusercontent.com/1002162/153035507-ff833f73-87e4-4195-b0e1-8ffce0edd831.png">

## GH CLI (successful))

```
❯ DEBUG=2 PAGER=cat gh api graphql -f query='query { organization(login: "myorg") { projectNext(number: 111) { id }}}'
* Request at 2022-02-08 11:35:12.795697 -0500 EST m=+0.018307839
* Request to https://api.github.com/graphql
* Request took 440.105405ms
{
  "data": {
    "organization": {
      "projectNext": {
        "id": "Redacted"
      }
    }
  }
}
```

Node Version: `v16.13.2`
Octokit: `octokit@1.7.1`

Any help would be greatly appreciated, thanks!

**Comment by apsamuel** [comment]
Update: this was related to the permissions on the token, both `org:read` and `org:write` are needed to interact with GH GraphQL API. Going to close this one.

**Comment by josefaidt** [comment]
Hey @apsamuel I'm running into this as well but have those two org permissions. Did you have to give your token admin access to get it to work?
