### ISSUE TITLE
Possibility to use custom reviver in deserialization?

### ISSUE THREAD

**Issue by hansmbakker** [octokit/graphql.js#414]
Is it possible to use custom revivers in the deserialization, so that `Date` strings could be serialized back directly to `Date` objects?

See https://stackoverflow.com/a/35923990/1114918 for reference.

Should I maybe do something with a custom `fetch` implementation?

**Comment by hansmbakker** [comment]
(likely this needs to be answered in https://github.com/octokit/request.js/issues/538)

**Comment by gr2m** [comment]
closing in favor of https://github.com/octokit/request.js/issues/538
