### ISSUE TITLE
[BUG]: Uncaught TypeError: Cannot read properties of undefined (reading 'map') - 

### ISSUE THREAD

**Issue by ianFar96** [octokit/graphql.js#485]
### What happened?

My web-app uses octokit/graphql.js to fetch pull requests, until two days ago it worked like a charm, now coincidentally with the `6.0.0` breaking version I get this error in the console: `Uncaught TypeError: Cannot read properties of undefined (reading 'map') - endpoint.js`. 
![image](https://github.com/octokit/graphql.js/assets/30315670/149e1f82-d6cc-4457-bda3-8f4a268cabfa)

This is how I declare the defaults:

```typescript
this.githubGraphql = graphql.defaults({
	baseUrl: config.baseUrl,
	headers: {
		Accept: 'application/vnd.github+json',
		authorization: `token ${config.auth}`,
	},
});
```

And this is how I make the calls:

```typescript
this.githubGraphql<{node: GithubGraphqlProjectResponse}>({query: `{
	node(id: "${mergeRequest.projectId}"){
		... on Repository {
			id
			name
		}
	}
}`})
```

### Versions

Octokit.js v5.0.5 and 6.0.0 (tried also the new one with no success)

### Relevant log output

```shell
Uncaught TypeError: Cannot read properties of undefined (reading 'map') - endpoint.js
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wolfy1339** [comment]
What version of `@octokit/endpoint` is being pulled in via `@octokit/request`?

This bug was fixed in https://github.com/octokit/endpoint.js/pull/427

**Comment by wolfy1339** [comment]
The proper fix for web users is to upgrade `@octokit/endpoint` in `@octokit/request`, and update it here, then release it
