### ISSUE TITLE
How can I retrieve the date an issue was added to a projectV2 using Github's GRAPHQL api?

### ISSUE THREAD

**Issue by Coroxx** [octokit/graphql.js#506]
### Describe the need

I'm working on a Github automation script, for a specific task I need to know from a projectV2 and an issue number, get the date when the issue was added using the graphQL api.

I tried projectcards but it concerns only the project item and not the projectV2. I tried to look at the REST Api but same, cannot found this information (?)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gr2m** [comment]
You can retrieve the `createdAt` timestamp for a `ProjectV2Item` which is the time an issue is added to a project (unless you created the issue from a draft item)

```graphql
{
  node(id: "PVTI_lAHNnDjOAAEhCM4CbBBn") {
    ... on ProjectV2Item {
      createdAt
    }
  }
}
```
