### ISSUE TITLE
[FEAT]: Return type for TS

### ISSUE THREAD

**Issue by nvmnghia** [octokit/graphql.js#522]
### Describe the need

Example query:

```graphql
mutation prrt($input: AddPullRequestReviewThreadInput!) {
    addPullRequestReviewThread(input: $input) {
        thread {
            id
        } } }
```

Using Octokit, I have to type like this:

```typescript
const mutateFn = graphql<{
    addPullRequestReviewThread: AddPullRequestReviewThreadPayload;
}>;
const response = await mutateFn(mutation, { input, headers });
```

The `addPullRequestReviewThread: ` part is quite long. Can this be automated/inferred somehow? I'd like to just specify the payload type `AddPullRequestReviewThreadPayload`, or something like `AddPullRequestReviewThreadPayloadWrapper`. Or is this required in all GraphQL?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gr2m** [comment]
Schema types can be imported from `@octokit/graphql-schema`:
https://github.com/octokit/graphql-schema#schema-as-types

Does that help?

**Comment by nvmnghia** [comment]
> Schema types can be imported from `@octokit/graphql-schema`: [octokit/graphql-schema#schema-as-types](https://github.com/octokit/graphql-schema#schema-as-types)
> 
> Does that help?

No, that's what I've been using. I want to get rid of the *field name* inside the return type. For example, I don't want to write this:

```ts
const { repository } = await graphql<{ repository: Repository }>()
```

and I want to write this:

```ts
const repository = await graphql<Repository>()
```

or at least this:

```ts
const { repository } = await graphql<GetRepository>()
```

**Comment by gr2m** [comment]
I'm not sure how that could work, it looks like you want to change the behavior of the `graphql()` method based on the type parameter, that's not possible.
