### ISSUE TITLE
[FEAT]: GraphQL: Ensure Order of [Processing of] Mutations

### ISSUE THREAD

**Issue by MarkusMit** [octokit/graphql.js#523]
### Describe the need

I would like to migrate a project using GitHub REST API to GraphQL API, at least in parts, because I'm hoping for a performance improvement due to the reduced number of requests by combining multiple mutiations in one requests using aliases.

However, in some cases the order of the calls is relevant, and now I'm wondering if (and how) I can make sure, that 

 -  (a) the mutations are processed sequentially and in the order as defined in the request
 -  (b) _(much more important)_ in case of an error in one mutation, all further mutations are not executed at all?

Is there already some feature available (currently on GitHub Enterprise Server 3.8), or would this be a new feature?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gr2m** [comment]
`@octokit/graphql` is just sending the graphql query to GitHub and returning the result. I'm not sure how GitHub handles mutations, the question would be better asked in https://github.com/orgs/community/discussions/categories/api-and-webhooks. There is nothing we can do within @octokit about it
