### ISSUE TITLE
[BUG]: getting unicorn HTML in an error response

### ISSUE THREAD

**Issue by ljharb** [octokit/graphql.js#554]
### What happened?

I run `npx repo-report ls` which runs a graphql query using a GH_TOKEN in the environment, to list all the repos you have access to.

in response, i get a unicorn response with html that starts with:
```
RequestError [HttpError]: <!DOCTYPE html>
<!--

Hello future GitHubber! I bet you're here to remove those nasty inline styles,
DRY up these templates and make 'em nice and re-usable, right?

Please, don't. https://github.com/styleguide/templates/2.0

-->
<html>
  <head>
    <title>Unicorn! &middot; GitHub</title>
```

I'm using v5 of this library, which worked fine before with no changes.

Is this a known thing with this version, or is it a Github API problem?

### Versions

Octokit v5.0.6, node v21.6.2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wolfy1339** [comment]
Are yous sure on the version number?
It's not a valid version for either the
- `octokit`
- `@octokit/core`
- `@octokit/graphql`

This seems like a GitHub API problem

**Comment by ljharb** [comment]
Yes, v5.0.6 of `@octokit/graphql`, which is absolutely a valid version number, as you can verify with `npm show @octokit/graphql@5.0.6`

**Comment by wolfy1339** [comment]
The unicorn error is definitely something wrong on GitHub's side. The underlying code hasn't really changed for a couple years

**Comment by ljharb** [comment]
Thanks; I'll file a ticket.
