### ISSUE TITLE
[FEAT]: Custom Properties (Queryable & Mutation to set/update).

### ISSUE THREAD

**Issue by chriseaton** [octokit/graphql.js#578]
### Describe the need

We're having good luck leveraging GitHub's graphql for our organization's needs, but recently hit a roadblock trying to leverage the Custom Properties feature, which doesn't look like it's made it yet into Octokit GraphQL. It is in the REST API, which we'll use as a fallback, but it would be nice if it was available. So far it's the only resource we _haven't_ been able to leverage in GraphQL so it stands out.

Ideally we'd be able to retrieve the custom properties using our fg token for the organization `type Organization` and individual respositories `type Repository`- the repositories being the most needed. Additionally being able to update or set the value of the custom properties easily via mutation for specific repositories is equally important.

### API Version

GraphQL API 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wolfy1339** [comment]
It doesn't seem to be present in the GraphQL API yet, and we don't control that.

We download a copy of the GraphQL schema from GitHub regularly over in https://github.com/octokit/graphql-schema/

It will be available whenever GitHub decides to implement it
