### ISSUE TITLE
Adding typings

### ISSUE THREAD

**Issue by ocombe** [octokit/graphql.js#6]
Hello, I've been using `@octokit/rest` for a while, and started porting my code to graphql, but I'm missing the typings that were super useful (https://github.com/octokit/rest.js/blob/master/scripts/templates/index.d.ts.tpl)
Would you consider adding something similar for graphql?

**Comment by gr2m** [comment]
Yes :) I think @jasonetco was looking into adding them as well, or to rewrite the lib in Typescript altogether. Feel free to get it started :)

**Comment by JasonEtco** [comment]
I started rewriting the lib in TypeScript this morning 😆 I'm far from being done though. Will share what I've got soon!

**Comment by gr2m** [comment]
@JasonEtco 🛎👆

**Comment by gr2m** [comment]
@JasonEtco 🛎 Still working on it?

**Comment by JasonEtco** [comment]
I am not - I had basic typings, but nothing that'd be good enough to share, probably only 20 minutes worth of work 😬

**Comment by gr2m** [comment]
Do you want to start a PR with what you got and maybe someone else can pick it up from there?

**Comment by JasonEtco** [comment]
Done @gr2m 👍 #13

**Comment by gr2m** [comment]
done via [v4.0.0](https://github.com/octokit/graphql.js/releases/tag/v4.0.0)
