### ISSUE TITLE
Can't load client in Cloudflare workers

### ISSUE THREAD

**Issue by olivernybroe** [octokit/graphql.js#78]
When trying to use this library inside a Cloudflare Worker it crashes with following error message
```
Uncaught ReferenceError: navigator is not defined
```

This happens when adding 
```
import { graphql } from "@octokit/graphql";
```

**Comment by gr2m** [comment]
Oh interesting, thanks for letting me know! I'm fairly sure the fix need to happen here:
https://github.com/gr2m/universal-user-agent/blob/d2960698eedb776000df9cd7b70d26c5574835f4/src/browser.ts

In the future we might provide a custom export for cloudlfare, but for the time being I think we can just add a check if `navigator` exists, and if it does not then return `unknown`, maybe with a reference to this issue?

Would you like to send a PR?

**Comment by olivernybroe** [comment]
@gr2m thanks for debugging this and figuring out where the error originated from!

I created a PR 👍

**Comment by gr2m** [comment]
Is your project Open Source? I've a project in mind for Cloudflare Workers myself and would be interested how your setup looks like

All I've built so far is a GitHub OAuth client server https://github.com/gr2m/cloudflare-worker-github-oauth-login

**Comment by olivernybroe** [comment]
@gr2m Unfortunately it is closed source for now. In a couple of months I'll prob. open source it, just need to clean it first and so on.

However the cloudflare worker part is not that big in my project. It is a simple service for creating a shield.io compatible API, where it uses the GitHub API to check if you have access to update the badge on the specified branch. (The request to the worker is coming from a GitHub Action)

**Comment by olivernybroe** [comment]
@gr2m Totally forgot to write here, but the project has been open sourced, so you can check it out.

You can find it here https://github.com/worksome/phpinsights-app/tree/master/badge

**Comment by gr2m** [comment]
I want to give this another look :)

**Comment by copperwall** [comment]
@gr2m I was testing this out with CF workers and the most recent release of `@octokit/graphql.js` and it seems to be working alright since these commits

https://github.com/gr2m/universal-user-agent/commit/d45e9dd24608ca0bf84fbb66d47871ebd391a124
https://github.com/gr2m/universal-user-agent/commit/a52f68818026142a08c3b0b83f90faa6ec993972

The test worker I have is live here https://my-app.copperwall.workers.dev/ and the worker code looks like

```ts
import { graphql } from '@octokit/graphql'

export async function handleRequest(request: Request): Promise<Response> {
  const { repository } = await graphql(
    `
      {
        repository(owner: "octokit", name: "graphql.js") {
          issues(last: 3) {
            edges {
              node {
                title
                url
                number
              }
            }
          }
        }
      }
    `,
    {
      headers: {
        authorization: `token ${GITHUB_TOKEN}`,
      },
    },
  )
  return new Response(
    `
                      <h1>Super Cool Test Site</h1>

                      <h2>GitHub Issues from GraphQL API</h2>
                      <ul>
                        ${repository.issues.edges.map((edge: any) => {
                          const { title, number, url } = edge.node
                          return `<a href="${url}"><li>#${number} ${title}</li></a>`
                        })}
                      </ul>
                      `,
    {
      headers: {
        'content-type': 'text/html;charset=UTF-8',
      },
    },
  )
}
```

Do you think there's more improvement for this issue, or does this seem fixed to you?

**Comment by gr2m** [comment]
woah very cool, thanks for setting up a worker just for this issue :) 

Yeah I'm pretty sure that the changes in universal-user-agent resolved the problem for good, we can close this issue
