### ISSUE TITLE
Incorrect return type for `graphql()`

### ISSUE THREAD

**Issue by sqren** [octokit/graphql.js#80]
Hi :octocat: 

I'm trying to run some of the examples from the readme and I'm seeing some odd return types:

**Example:**

```js
const { repository } = await graphql(`
    {
      repository(owner: "octokit", name: "graphql.js") {
        issues(last: 3) {
          edges {
            node {
              title
            }
          }
        }
      }
    }
);
```

The error I get is:
```
Property 'respoitory' does not exist on type 'GraphQlQueryResponseData'.ts(2339)
```

![image](https://user-images.githubusercontent.com/209966/75295655-7cde4180-582b-11ea-9907-d67d8f4eb3b6.png)

I understand that since the query is provided dynamically it is not possible for Typescript to determine the exact return type. I'd therefore expect it to be possible to provide a data return type like:

```ts
const { respoitory } = await graphql<{ repository: { ... }}>(
```

What is the suggested approach?

Thanks!

**Comment by gr2m** [comment]
I thought your suggestion was already possible, but looks like we only discussed it so far. 

I think for one, TypeScript should not raise the error, the result type should always be an object with any keys allowed.

And second, I agree we should support allowing to pass custom types. Would you like to start a pull request for this?

**Comment by seed-of-apricot** [comment]
@gr2m The suggestion from @sqren is not yet possible.

When I try

```ts
  const { repository } = await octokit.graphql<{ repository: any }>(
    `
      {
        repository(owner: "octokit", name: "graphql.js") {
        ...
```

It complains `Expected 0 type arguments, but got 1.ts(2558)`.

**Comment by gr2m** [comment]
I can't helpw ith `@actions/github`, see also https://github.com/actions/toolkit/issues/334#issuecomment-597298204

Could you try and use `@octokit/action` instead?

```js
import { Octokit } from '@octokit/action';

// `env.GITHUB_TOKEN` or `with.GITHUB_TOKEN` must be set in your .yaml workflow file
const octokit = new Octokit()
```

**Comment by seed-of-apricot** [comment]
@gr2m I still get the same issues. With `"@octokit/action": "^2.0.3"`.

![image](https://user-images.githubusercontent.com/26666870/77951629-3727f500-727f-11ea-8588-a4b55f4b5d39.png)

![image](https://user-images.githubusercontent.com/26666870/77951675-48710180-727f-11ea-9c79-a51f1a5d7314.png)

**Comment by gr2m** [comment]
Okay, thank you for checking. I promise I'll get back to this issue, I have it in my backlog. Just cannot make promises when. 

I'd gladly review a pull request, that would speed up the process a lot.

**Comment by copperwall** [comment]
Hey @gr2m, I’m interested in working on this if that’s alright. I’m having a little trouble passing a generic type that would let a user specify the return type from the exported `graphql` function down to the function in `graphql` function in `graphql.js`, but I’m kind of learning typescript as I go so I probably just need to spend a little more time on it.

**Comment by gr2m** [comment]
@copperwall of course! Thanks a lot for looking into it!
