### ISSUE TITLE
Feature Request: Add option to ignore GraphQL errors

### ISSUE THREAD

**Issue by dominguezcelada** [octokit/graphql.js#86]
## Description
I'm experiencing an issue using a Preview Schema from Github. Even the request succeeds and it retrieves the data I'm expecting, it also replies with errors. Since there are errors, I can't use `@octokit/graphql` utility to get the response.

Already reported [here](https://github.community/t5/GitHub-API-Development-and/What-does-the-quot-loading-quot-error-message-mean-in-response/td-p/33453) to Github :octocat: 

**Example Request**
```graphql
query($org: String!) {
    organization(login: $org) {
        repositories(first: 100) {
            nodes {
                name
                dependencyGraphManifests(first: 1) {
                    nodes {
                        dependenciesCount
                    }
                }
            }
        }
    }
}
```

**Example Response**
```json
{
   "data": { "organization": ...}
   "errors": [ ... ]
}
```
<details>
<summary>
See full example
</code>
</summary>
<code>
{
    "data": {
        "organization": {
            "repositories": {
                "nodes": [
                    {
                        "name": "Repo1",
                        "dependencyGraphManifests": {
                            "nodes": []
                        }
                    },
                    {
                        "name": "Repo2",
                        "dependencyGraphManifests": {
                            "nodes": [
                                {
                                    "dependenciesCount": 1
                                }
                            ]
                        }
                    }
                ]
            }
        }
    },
    "errors": [
        {
            "path": [
                "organization",
                "repositories",
                "nodes",
                8,
                "dependencyGraphManifests"
            ],
            "locations": [
                {
                    "line": 6,
                    "column": 17
                }
            ],
            "message": "loading"
        },
        {
            "path": [
                "organization",
                "repositories",
                "nodes",
                34,
                "dependencyGraphManifests"
            ],
            "locations": [
                {
                    "line": 6,
                    "column": 17
                }
            ],
            "message": "loading"
        }
    ]
}
</code>
</details>

## Proposal
To add option when creating `graphql(request, query,`**`options)`** to skip this check: 
https://github.com/octokit/graphql.js/blob/34b06cb0268e6dc90d3e983f8b14331538bd5a8b/src/graphql.ts#L19-L23

Something like `allowResponseErrors: true` and set it as `false` by default. 

https://github.com/octokit/graphql.js/blob/34b06cb0268e6dc90d3e983f8b14331538bd5a8b/src/graphql.ts#L47

**Comment by gr2m** [comment]
I think `error.data` should still give you access to the response?

**Comment by dominguezcelada** [comment]
> I think `error.data` should still give you access to the response?

Yes! You are right! It solves my use case and it's cleaner than adding this `allowErrors` option. Thanks! :D
